package Harmonioncraft.common.dimension;

import net.minecraft.src.BiomeGenBase;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHMCBiomes extends GenLayer
{
    protected BiomeGenBase[] commonBiomes;
    protected BiomeGenBase[] rareBiomes;

    public GenLayerHMCBiomes(long var1, GenLayer var3)
    {
        super(var1);
        this.commonBiomes = new BiomeGenBase[] {HMCBiomeBase.twilightForest, HMCBiomeBase.twilightForest2, HMCBiomeBase.highlands, HMCBiomeBase.mushrooms, HMCBiomeBase.swamp, HMCBiomeBase.clearing, HMCBiomeBase.darkForest};
        this.rareBiomes = new BiomeGenBase[] {HMCBiomeBase.tfLake, HMCBiomeBase.glacier, HMCBiomeBase.deepMushrooms, HMCBiomeBase.enchantedForest, HMCBiomeBase.fireSwamp};
        this.parent = var3;
    }

    public GenLayerHMCBiomes(long var1)
    {
        super(var1);
        this.commonBiomes = new BiomeGenBase[] {HMCBiomeBase.twilightForest, HMCBiomeBase.twilightForest2, HMCBiomeBase.highlands, HMCBiomeBase.mushrooms, HMCBiomeBase.swamp, HMCBiomeBase.clearing, HMCBiomeBase.darkForest};
        this.rareBiomes = new BiomeGenBase[] {HMCBiomeBase.tfLake, HMCBiomeBase.glacier, HMCBiomeBase.deepMushrooms, HMCBiomeBase.enchantedForest, HMCBiomeBase.fireSwamp};
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = IntCache.getIntCache(var3 * var4);

        for (int var6 = 0; var6 < var4; ++var6)
        {
            for (int var7 = 0; var7 < var3; ++var7)
            {
                this.initChunkSeed((long)(var7 + var1), (long)(var6 + var2));

                if (this.nextInt(15) == 0)
                {
                    var5[var7 + var6 * var3] = this.rareBiomes[this.nextInt(this.rareBiomes.length)].biomeID;
                }
                else
                {
                    var5[var7 + var6 * var3] = this.commonBiomes[this.nextInt(this.commonBiomes.length)].biomeID;
                }
            }
        }

        return var5;
    }
}