package Harmonioncraft.common.dimension;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHMCClearMinorFeatures extends GenLayer
{
    private static final int SCAN = 3;
    private static final int DSCAN = 6;

    public GenLayerHMCClearMinorFeatures(long var1, GenLayer var3)
    {
        super(var1);
        this.parent = var3;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.parent.getInts(var1 - 3, var2 - 3, var3 + 6, var4 + 6);
        int[] var6 = IntCache.getIntCache(var3 * var4);

        for (int var7 = 0; var7 < var4; ++var7)
        {
            for (int var8 = 0; var8 < var3; ++var8)
            {
                this.initChunkSeed((long)(var8 + var1), (long)(var7 + var2));
                int var9 = var5[var8 + 3 + (var7 + 3) * (var3 + 6)];

                if (var9 > 0 && var9 < HMCBiomeBase.majorFeature.biomeID)
                {
                    boolean var10 = true;

                    for (int var11 = 0; var11 <= 6; ++var11)
                    {
                        for (int var12 = 0; var12 <= 6; ++var12)
                        {
                            int var13 = var5[var8 + var12 + (var7 + var11) * (var3 + 6)];

                            if (var13 >= var9 && (var11 != 3 || var12 != 3))
                            {
                                var10 = false;
                            }
                        }
                    }

                    var6[var8 + var7 * var3] = var10 ? var9 : 0;
                    var5[var8 + 3 + (var7 + 3) * (var3 + 6)] = var6[var8 + var7 * var3];
                }
                else
                {
                    var6[var8 + var7 * var3] = var9;
                }
            }
        }

        return var6;
    }
}
