package Harmonioncraft.common.dimension;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHMCFeatureZoom  extends GenLayer {
	
    public boolean shiftCenter;

    public GenLayerHMCFeatureZoom(long var1, GenLayer var3, boolean var4)
    {
        super(var1);
        super.parent = var3;
        this.shiftCenter = var4;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int var5 = var1 >> 1;
        int var6 = var2 >> 1;
        int var7 = (var3 >> 1) + 3;
        int var8 = (var4 >> 1) + 3;
        int[] var9 = this.parent.getInts(var5, var6, var7, var8);
        int[] var10 = IntCache.getIntCache(var7 * 2 * var8 * 2);
        int var11 = var7 << 1;
        int var13;

        for (int var12 = 0; var12 < var8 - 1; ++var12)
        {
            for (var13 = 0; var13 < var7 - 1; ++var13)
            {
                var10[var13 * 2 + 0 + (var12 * 2 + 0) * var11] = var9[var13 + var12 * var7];
                var10[var13 * 2 + 1 + (var12 * 2 + 0) * var11] = 0;
                var10[var13 * 2 + 0 + (var12 * 2 + 1) * var11] = 0;
                var10[var13 * 2 + 1 + (var12 * 2 + 1) * var11] = 0;
            }
        }

        int[] var14 = IntCache.getIntCache(var3 * var4);

        for (var13 = 0; var13 < var4; ++var13)
        {
            System.arraycopy(var10, (var13 + (var2 & 1)) * (var7 << 1) + (var1 & 1), var14, var13 * var3, var3);
        }

        return var14;
    }

    public static GenLayer multipleZoom(long var0, GenLayer var2, int var3)
    {
        Object var4 = var2;

        for (int var5 = 0; var5 < var3; ++var5)
        {
            var4 = new GenLayerHMCFeatureZoom(var0 + (long)var5, (GenLayer)((GenLayer)var4), false);
        }

        return (GenLayer)((GenLayer)var4);
    }
}