package Harmonioncraft.common.dimension;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHMCMinorFeatures extends GenLayer
{
    protected GenLayer biomeLayer;

    public GenLayerHMCMinorFeatures(int var1, GenLayer var2, GenLayer var3)
    {
        super((long)var1);
        this.parent = var3;
        this.biomeLayer = var2;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int var5 = var3 + 2;
        int[] var6 = this.biomeLayer.getInts(var1 - 1, var2 - 1, var5, var4 + 2);
        int[] var7 = this.parent.getInts(var1, var2, var3, var4);
        int[] var8 = IntCache.getIntCache(var3 * var4);

        for (int var9 = 0; var9 < var4; ++var9)
        {
            for (int var10 = 0; var10 < var3; ++var10)
            {
                this.initChunkSeed((long)(var10 + var1), (long)(var9 + var2));
                int var11 = var7[var10 + var9 * var3];
                int var12 = var6[var10 + 1 + (var9 + 1) * var5];

                if (HMCBiomeBase.isFeature(var11))
                {
                    var8[var10 + var9 * var3] = var11;
                }
                else if (this.nextInt(2) == 0)
                {
                    int var13 = var6[var10 + 1 + (var9 + 0) * var5];
                    int var14 = var6[var10 + 2 + (var9 + 1) * var5];
                    int var15 = var6[var10 + 0 + (var9 + 1) * var5];
                    int var16 = var6[var10 + 1 + (var9 + 2) * var5];
                    int var17 = var6[var10 + 0 + (var9 + 0) * var5];
                    int var18 = var6[var10 + 2 + (var9 + 2) * var5];
                    int var19 = var6[var10 + 2 + (var9 + 0) * var5];
                    int var20 = var6[var10 + 0 + (var9 + 2) * var5];

                    if (var17 == var12 && var18 == var12 && var19 == var12 && var20 == var12 && var13 == var12 && var14 == var12 && var15 == var12 && var16 == var12)
                    {
                        var8[var10 + var9 * var3] = this.nextInt(HMCBiomeBase.majorFeature.biomeID);
                    }
                    else
                    {
                        var8[var10 + var9 * var3] = 0;
                    }
                }
                else
                {
                    var8[var10 + var9 * var3] = 0;
                }
            }
        }

        return var8;
    }
}
