package Harmonioncraft.common.dimension;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHMCReinsertFeatures extends GenLayer
{
    private GenLayer withoutLayer;
    private GenLayer withLayer;

    public GenLayerHMCReinsertFeatures(long var1, GenLayer var3, GenLayer var4)
    {
        super(var1);
        this.withoutLayer = var3;
        this.withLayer = var4;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long var1)
    {
        this.withoutLayer.initWorldGenSeed(var1);
        this.withLayer.initWorldGenSeed(var1);
        super.initWorldGenSeed(var1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.withoutLayer.getInts(var1, var2, var3, var4);
        int[] var6 = this.withLayer.getInts(var1, var2, var3, var4);
        int[] var7 = IntCache.getIntCache(var3 * var4);

        for (int var8 = 0; var8 < var3 * var4; ++var8)
        {
            if (var6[var8] > 0)
            {
                var7[var8] = var6[var8] == HMCBiomeBase.majorFeature.biomeID ? var6[var8] : HMCBiomeBase.minorFeature.biomeID;
            }
            else
            {
                var7[var8] = var5[var8];
            }
        }

        return var7;
    }
}
