package net.Harmonioncraft.world.genlayer;

import net.minecraft.src.BiomeGenBase;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerDownfall extends GenLayer
{
    public GenLayerDownfall(GenLayer var1)
    {
        super(0L);
        this.parent = var1;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.parent.getInts(var1, var2, var3, var4);
        int[] var6 = IntCache.getIntCache(var3 * var4);

        for (int var7 = 0; var7 < var3 * var4; ++var7)
        {
            var6[var7] = BiomeGenBase.biomeList[var5[var7]].getIntRainfall();
        }

        return var6;
    }
}
