package net.Harmonioncraft.world.genlayer;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHarmonionSmallIslands extends GenLayerHarmonion
{
    public GenLayerHarmonionSmallIslands(long var1, GenLayer var3)
    {
        super(var1);
        this.parent = var3;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int var5 = var1 - 1;
        int var6 = var2 - 1;
        int var7 = var3 + 2;
        int var8 = var4 + 2;
        int[] var9 = this.parent.getInts(var5, var6, var7, var8);
        int[] var10 = IntCache.getIntCache(var3 * var4);

        for (int var11 = 0; var11 < var4; ++var11)
        {
            for (int var12 = 0; var12 < var3; ++var12)
            {
                int var13 = var9[var12 + 0 + (var11 + 0) * var7];
                int var14 = var9[var12 + 2 + (var11 + 0) * var7];
                int var15 = var9[var12 + 0 + (var11 + 2) * var7];
                int var16 = var9[var12 + 2 + (var11 + 2) * var7];
                int var17 = var9[var12 + 1 + (var11 + 1) * var7];
                this.initChunkSeed((long)(var12 + var1), (long)(var11 + var2));

                if (var17 == 60 && var13 == 60 && var14 == 60 && var15 == 60 && var16 == 60 && (this.nextInt(300) == 0 || this.nextInt(350) == 0 || this.nextInt(450) == 0))
                {
                    var10[var12 + var11 * var3] = 61 + this.nextInt(4);
                }
                else
                {
                    var10[var12 + var11 * var3] = var17;
                }
            }
        }

        return var10;
    }
}
