package net.Harmonioncraft.world.genlayer;

import net.Harmonioncraft.world.biomes.BiomeGenHarmonion;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHarmonionAddBiomes extends GenLayerHarmonion
{
    int[] biomes;

    public GenLayerHarmonionAddBiomes(long var1, GenLayer var3)
    {
        super(var1);
        this.biomes = new int[] {BiomeGenHarmonion.Harmonion.biomeID, BiomeGenHarmonion.rainforestPlains.biomeID};
        this.parent = var3;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.parent.getInts(var1, var2, var3, var4);
        int[] var6 = IntCache.getIntCache(var3 * var4);

        for (int var7 = 0; var7 < var4; ++var7)
        {
            for (int var8 = 0; var8 < var3; ++var8)
            {
                this.initChunkSeed((long)(var8 + var1), (long)(var7 + var2));
                int var9 = var5[var8 + var7 * var3];

                if (var9 != 60)
                {
                    if (this.nextInt(3) == 0)
                    {
                        var6[var8 + var7 * var3] = BiomeGenHarmonion.rainforestPlains.biomeID;
                    }
                    else
                    {
                        var6[var8 + var7 * var3] = BiomeGenHarmonion.Harmonion.biomeID;
                    }
                }
                else
                {
                    var6[var8 + var7 * var3] = BiomeGenHarmonion.HarmonionOcean.biomeID;
                }
            }
        }

        return var6;
    }
}
