package net.Harmonioncraft.world.genlayer;

import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class GenLayerHarmonionRiverMix extends GenLayerHarmonion
{
    /** parent GenLayer that was provided via the constructor */
    private GenLayer parent;
    private GenLayer river;

    public GenLayerHarmonionRiverMix(long var1, GenLayer var3, GenLayer var4)
    {
        super(var1);
        this.parent = var3;
        this.river = var4;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long var1)
    {
        this.parent.initWorldGenSeed(var1);
        this.river.initWorldGenSeed(var1);
        super.initWorldGenSeed(var1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.parent.getInts(var1, var2, var3, var4);
        int[] var6 = this.river.getInts(var1, var2, var3, var4);
        int[] var7 = IntCache.getIntCache(var3 * var4);

        for (int var8 = 0; var8 < var3 * var4; ++var8)
        {
            if (var5[var8] == 60)
            {
                var7[var8] = var5[var8];
            }
            else if (var6[var8] >= 0)
            {
                var7[var8] = var6[var8];
            }
            else
            {
                var7[var8] = var5[var8];
            }
        }

        return var7;
    }
}
